import turtle
tt= turtle.Turtle()
tt.pensize(6)
tt.speed(1) 
tt.color('blue')  
tt.penup() 
tt.goto(-100,-25)  
tt.pendown()
tt.circle(51) 
tt.color('black')  
tt.penup() 
tt.goto(10,-25)  
tt.pendown() 
tt.circle(51)  
tt.color('red')  
tt.penup()  
tt.goto(120,-25)  
tt.pendown() 
tt.circle(51) 
tt.color('yellow')  
tt.penup()
tt.goto(-45,-75)  
tt.pendown() 
tt.circle(51) 
tt.color('green')  
tt.penup()  
tt.goto(65,-75)  
tt.pendown() 
tt.circle(51)  
tt.penup()
tt.goto(200,-200)
tt.color('purple')
style = ('Courier', 45, 'normal')
tt.write('SASI', font=style, align='center')
tt.hideturtle()
tt.done()